server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /proxy/mototally/ {
        proxy_pass https://www.moto-tally.com/;
        proxy_set_header Host www.moto-tally.com;
        proxy_ssl_server_name on;
        proxy_set_header Accept-Encoding "";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
